server:
  host: "localhost"
  port: 8080
  #basicAuth:                # optional
  #  user: "joe"             # optional
  #  password: "secret"      # optional

mkdocs:
  projectPath: "D:\\mkdocsrest-test"
  # configFile: "D:/mkdocsrest-test/mkdocs.yaml"  # optional
  # docsPath: "D:/mkdocsrest-test/docs"           # optional