server:
  host: "0.0.0.0"
  port: 8080
  basicAuth:                # optional
    user: "joe"             # optional
    password: "secret"      # optional
  #cors:                     # optional
  #  allowedorigins:
  #    - "https://wiki.mycompany.com"
  #  allowedmethods:
  #    - HEAD
  #    - GET
  #    - PUT
  #    - POST
  #    - DELETE

mkdocs:
  projectPath: "/home/markus/documents/Wiki"
  # configFile: "D:/mkdocsrest-test/mkdocs.yaml"  # optional
  # docsPath: "D:/mkdocsrest-test/docs"           # optional