name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Genereat build files
        run: |
          GOOS="linux"
          GOARCH="amd64"
          filename="$GOOS-$GOARCH"
          go build -o ./dist/mkdocs-backend-$filename -buildmode "exe" main.go

      - name: Genereat build files
        run: |
          GOOS="linux"
          GOARCH="arm64"
          filename="$GOOS-$GOARCH"
          go build -o ./dist/mkdocs-backend-$filename -buildmode "exe" main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/mkdocs-backend-linux-amd64
            dist/mkdocs-backend-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
